name: ⚡ Performance Issue
description: Report a performance problem or slow behavior
title: "[Performance]: "
labels: ["performance", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a performance issue! Please provide as much detail as possible to help us investigate.

  - type: textarea
    id: performance-problem
    attributes:
      label: ⚡ Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: The API is slow when... / Response times are high for... / Memory usage increases when...
    validations:
      required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: 📋 Performance Issue Type
      description: What type of performance issue is this?
      options:
        - "Slow API response times"
        - "High memory usage"
        - "CPU usage spikes"
        - "Slow server startup"
        - "Route resolution performance"
        - "OpenAPI generation slow"
        - "Large bundle size"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: ⚡ Expected Performance
      description: What performance did you expect?
      placeholder: I expected response times under... / Memory usage should be... / Startup time should be...
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: 📊 Actual Performance
      description: What performance are you actually seeing? Include specific metrics if possible.
      placeholder: Response times are... / Memory usage is... / CPU usage reaches... / Startup time is...
    validations:
      required: true

  - type: textarea
    id: performance-metrics
    attributes:
      label: 📈 Performance Metrics
      description: Please provide specific performance measurements
      placeholder: |
        Response time: 2000ms (expected: 100ms)
        Memory usage: 500MB (expected: 50MB)
        Requests per second: 10 (expected: 100)
        Server startup time: 30s (expected: 5s)
      render: text
    validations:
      required: false

  - type: input
    id: koritsu-version
    attributes:
      label: Koritsu Version
      description: What version of Koritsu are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun Version
      description: What version of Bun are you using?
      placeholder: e.g., 1.3.1
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Where are you experiencing this performance issue?
      options:
        - "Development (local)"
        - "Staging/Testing"
        - "Production"
        - "CI/CD Pipeline"
        - "All environments"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Set up a server with...
        2. Create X number of routes...
        3. Send Y concurrent requests...
        4. Measure performance using...
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: 📝 Code Example
      description: Please provide code that demonstrates the performance issue
      placeholder: |
        ```typescript
        // Your code that shows the performance problem
        ```
      render: typescript
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: ⚙️ Configuration
      description: Share your Koritsu configuration that might affect performance
      placeholder: |
        ```typescript
        // Your configuration
        ```
      render: typescript
    validations:
      required: false

  - type: checkboxes
    id: profiling-done
    attributes:
      label: 🔬 Profiling Information
      description: What profiling or investigation have you done?
      options:
        - label: Used Bun's built-in profiler
        - label: Measured with console.time/timeEnd
        - label: Used external monitoring tools
        - label: Checked memory usage
        - label: Analyzed bundle size
        - label: Compared with previous versions
        - label: Tested with different configurations

  - type: textarea
    id: profiling-results
    attributes:
      label: 📊 Profiling Results
      description: Share any profiling data or analysis you've done
      placeholder: Share profiling output, flame graphs, memory snapshots, or other diagnostic information
      render: text
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: 🖥️ System Information
      description: Provide information about your system
      placeholder: |
        OS: macOS 14.0
        CPU: M2 Pro
        Memory: 32GB
        Node.js: 20.10.0 (if applicable)
        Docker: Yes/No
    validations:
      required: false

  - type: textarea
    id: workarounds
    attributes:
      label: 🛠️ Workarounds Tried
      description: What have you tried to improve the performance?
      placeholder: I've tried... / Changing configuration... / Different approaches...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: Any other information that might help us investigate the performance issue
      placeholder: This started happening when... / It's related to... / Similar issues...
    validations:
      required: false
