name: ❓ Question
description: Ask a question about usage or implementation
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Koritsu? Please fill out the form below.

        **Note**: For general discussions or community questions, consider using [GitHub Discussions](https://github.com/boyer-nicolas/koritsu/discussions) instead.

  - type: textarea
    id: question
    attributes:
      label: ❓ Your Question
      description: What would you like to know about Koritsu?
      placeholder: How do I... / What's the best way to... / Is it possible to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🎯 Context
      description: What are you trying to accomplish? Provide some background about your use case.
      placeholder: I'm building an API that needs to... / My application requires... / I want to implement...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: 🔍 What You've Tried
      description: What have you already tried? Include any code, configuration, or approaches you've attempted.
      placeholder: I've tried... / I looked at the documentation for... / I attempted to configure...
      render: typescript
    validations:
      required: false

  - type: input
    id: koritsu-version
    attributes:
      label: Koritsu Version
      description: What version of Koritsu are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: false

  - type: checkboxes
    id: related-areas
    attributes:
      label: 📋 Related Areas
      description: Which areas of Koritsu does your question relate to?
      options:
        - label: File-based routing
        - label: Configuration
        - label: OpenAPI/Swagger documentation
        - label: Request/Response handling
        - label: Validation (Zod schemas)
        - label: Error handling
        - label: TypeScript integration
        - label: Performance
        - label: Deployment
        - label: Testing
        - label: Other

  - type: textarea
    id: additional-info
    attributes:
      label: 🔍 Additional Information
      description: Any other details that might help us answer your question.
      placeholder: Here's my current setup... / I'm also using... / Related issues I've found...
    validations:
      required: false
